name: Notify when a pull request in main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify when someone creates pull request on main branch
        id: notify-on-pr
        uses: ./
  
      - name: Run
        run: echo 'Sending notification'
